---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGI6NTQzMg==  # This is base64 encoded: postgresql://user:password@db:5432

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: c2VjcmV0SldUU2VjcmV0S2V5  # This is base64 encoded: secretJWTSecretKey

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NEXT_PUBLIC_API_BASE_URL: "http://backend-service:8001"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"